export const ActionTypes = {
  CURRENT_DATA: "CURRENT_DATA",
  CURRENT_DATA_METRIC: "CURRENT_DATA_METRIC",
  CURRENT_DATA_IMPIRIAL: "CURRENT_DATA_IMPIRIAL",
  FORECAST: "FORECAST",
  FORECAST_METRIC: "FORECAST_METRIC",
  FORECAST_IMPERIAL: "FORECAST_IMPERIAL",
};
